version: '3'
services:
    front:
        build: ./front
        container_name: front
        volumes:
            - ./front:/front
        ports:
            - 3000:3000
        environment:
            - REACT_APP_BASE_URL=http://localhost:5000/api/zetter

    api:
        build: ./api
        container_name: api
        volumes:
            - ./api:/api
        ports:
            - 5000:5000
        environment:
            - DATABASE_URL: 'mysql://root@db:3306/mydb'

    db:
        container_name: mysql
        image: mysql:5.7
        ports:
            - 3306:3306
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
